### ISSUE TITLE
Sensor export needs fixing

### ISSUE THREAD

**Issue by AlCap23** [dfki-ric/phobos#153]
## Brief Description of the Issue
The current dump of the sensor information in *modelname*_sensors.yml is not formatted.

## Expected Behavior / New Workflow

Minimal Example:

```YAML
sensors:
- id:
  - collision_foot_left_2
  - collision_foot_left_1
  - collision_foot_left_3
  - collision_foot_left_4
  link: TargetCOS
  name: footForce0
  type: NodeContactForce
```

## Actual Behavior / Current Workflow

```YAML
- link: link_Joint_Pos
  name: Joint_Pos
  type: JointPosition
```

## Steps to Reproduce the Issue / Context in Which it Occurs

Include sensors within the model via "Add sensor" button.

## Operating System and Phobos Version

Ubuntu 16.04, Blender 2.79a, commit fa9638f759c65843b60cd58d4e524f950d368823 on master
